version: '3.8'

services:

  redis:
    image: redis:7-alpine
    container_name: mailflow-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    restart: unless-stopped

  maildev:
    image: maildev/maildev:latest
    container_name: mailflow-maildev
    ports:
      - "1025:1025" # SMTP port
      - "1080:80"   # Web UI port
    restart: unless-stopped

volumes:

  redisdata:
